# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_mymulti_wrappers", use_symbols = TRUE, package_name = "mymulti")

#' @usage NULL
#' @useDynLib mymulti, .registration = TRUE
NULL

#' @export
multiplicame_e_invierteme <- function(m1, m2) .Call(wrap__multiplicame_e_invierteme, m1, m2)


# nolint end
